name: SWPATH Sync Job
on:
  push:
    branches:
      - 'master'
    paths:  
      - 'sync/repo/Readme.md'
  workflow_dispatch:    
jobs:
  Sync:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Run Custom action
        id: capture
        uses: ./.github/actions/Example
        with:
          Name: Shankarsharmas
      - name: Display the outputs
        run: |
          echo "Messages to display for users: ${{ steps.capture.outputs.message }}"
      - name: Download the Artifacts
        uses: actions/download-artifact@v3
        with:
          name: my-artifact
          path: /files
         
                  
